/* Generated by cbindgen — do not edit */

#ifndef SWIFTLY_H
#define SWIFTLY_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct AcordDoc AcordDoc;

 struct AcordDoc *acord_doc_new(void);

 void acord_doc_free(struct AcordDoc *doc);

 void acord_doc_set_text(struct AcordDoc *doc, const char *text);

 char *acord_doc_get_text(const struct AcordDoc *doc);

 char *acord_doc_evaluate(struct AcordDoc *doc);

 char *acord_eval_line(const char *text);

 bool acord_doc_save(const struct AcordDoc *doc, const char *path);

 struct AcordDoc *acord_doc_load(const char *path);

 char *acord_cache_save(const struct AcordDoc *doc);

 struct AcordDoc *acord_cache_load(const char *uuid);

 char *acord_list_notes(void);

 char *acord_highlight(const char *source, const char *lang);

 void acord_free_string(char *s);

#endif  /* SWIFTLY_H */
