name: Acord
options:
  bundleIdPrefix: org.else-if
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: org.else-if.acord
    DEVELOPMENT_TEAM: Z9CXT3ZVLD
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: "2,1"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_OBJC_BRIDGING_HEADER: ../viewport/include/acord.h
    LIBRARY_SEARCH_PATHS:
      - $(PROJECT_DIR)/../target/$(SWIFT_PLATFORM_TARGET_PREFIX)/release
    OTHER_LDFLAGS:
      - -lacord_viewport
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
    INFOPLIST_FILE: Info.plist
    GENERATE_INFOPLIST_FILE: NO

targets:
  Acord:
    type: application
    platform: iOS
    sources:
      - path: src
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
    dependencies: []
